name: workflows

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main
jobs:
  excute-python:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Tokyo

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: excute python
        run: |
          python weibo_hot_search.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          add: "images"
          message: "Update images"
          author_name: "bot"
          author_email: "bot@github.com"